### PR TITLE
Connect backend to MongoDB

### LINKED ISSUE #5: Connecting MongoDB with FlaskAPI
As the title states.

We need this to make it possible to have a way to write/read data from the backend to the database, and vice versa.

### PR DESCRIPTION
**Pull request by baioc**
Closes #5 
A GET request on the server's `/` route now gives back a JSON containing dataset identification and one problem instance:
image

To get this minimum example working, you need to create a database in MongoDB called `demo`, with a `_datasets` collection.  
Then, I've added the following document to the `_datasets` collection:
```json
{
  "_id": "Tripix",
  "content_type": "IMAGE",
  "message": "Please select the label that best describes what is being captured in this photograph.",
  "label_type": "CLASS",
  "options": ["Visual Art (including statues and paintings)", "Objects", "People", "Animals", "Plants", "Sky", "Water", "Landscape", "Architecture (internal)", "Monuments (external)", "None / Unknown"]
}
```

Notice its id is `Tripix`, therefore I also create a `Tripix` collection under the `demo` database, which contains documents looking like:
```json
{
  "_id": "IMG_20210530_105501",
  "URL": "file:///home/baioc/Pictures/IMG_20210530_105501.jpg",
}
```

These are, repectively, the `"dataset"` and `"instance"` parts of the JSON received in the screenshot above.

### CODE REVIEW

**Comment by Rubix982** [comment]
LGTM.

**Comment by fissoreg** [comment]
This
```
{
  "_id": "IMG_20210530_105501",
  "URL": "file:///home/baioc/Pictures/IMG_20210530_105501.jpg",
}
```

should work on our machines if it's relative URLs:

{
  "_id": "IMG_20210530_105501",
  "URL": "assets/img/IMG_20210530_105501.jpg",
}

(or similar).

**Comment by Rubix982** [comment]
@baioc

**Comment by baioc** [comment]
`ACK`, will try to use some pictures of my own to test this

**Pull request merged**
